CREATE USER myuser;
CREATE DATABASE mydb;
GRANT ALL PRIVILEGES ON DATABASE mydb TO myuser;

-- Департаменты
CREATE TABLE departments (
    -- Тип данных bigint с ограничением generated as identity позволяет
    -- создать столбец с уникальным идентификатором для каждой строки.
    -- Уникальность обеспечивается монотонно возрастающей последовательностью чисел.
    -- @see: https://www.postgresql.org/docs/current/sql-createtable.html
    id BIGINT generated BY DEFAULT AS IDENTITY,
    parent_id BIGINT NOT NULL,
    name text NOT NULL,
 
    -- constraint primary key устанавливает ограничение целостности, указывающее,
    -- что значения в заданном столбце должны быть уникальные и не пустые (not null).
    -- Установка этого ограничения автоматически создаёт BTree-индекс для заданного столбца.
    -- @see: https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS
    CONSTRAINT departments_id_pkey PRIMARY KEY (id),
    -- constraint foreign key устанавливает связь между столбцами в текущей и заданной таблице.
    -- в данном случае связь рекурсивная, т.е. parent_id ссылается на запись в своей таблице (department).
    -- on delete cascade обозначает, что при удалении родительского департамента,
    -- все его наследники будут автоматически удалены.
    -- @see: https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK
    CONSTRAINT departments_fk_parent_id FOREIGN KEY (parent_id) REFERENCES departments (id) ON DELETE cascade
);
 
-- Должность
CREATE TABLE positions (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
 
    CONSTRAINT positions_id_pkey PRIMARY KEY (id)
);
 
-- Сотрудник
CREATE TABLE employees (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    firstname text NOT NULL,
    middlename text NOT NULL,
    lastname text NOT NULL,
    gender CHAR(1) NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    position_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    salary BIGINT NOT NULL,
    manager_id BIGINT NOT NULL,
    entry_at DATE NOT NULL,
 
    CONSTRAINT employees_id_pkey PRIMARY KEY (id),
    -- on delete restrict обозначает, что при удалении должности из таблицы position,
    -- произойдет ошибка если существует хотя бы один сотрудник, занимающий эту должность.
    -- @see: https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK
    CONSTRAINT employees_fk_position_id FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE RESTRICT,
    CONSTRAINT employees_fk_department_id FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT,
    -- На столбец salary устанавливается ограничение, требующее, чтобы зарплата была не отрицaтельным числом.
    -- @see: https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS
    CONSTRAINT employees_salary_not_negative_check CHECK (salary >= 0),
    CONSTRAINT employees_fk_manager_id FOREIGN KEY (manager_id) REFERENCES employees (id) ON DELETE RESTRICT
);
 